# Generated by Django 4.0.4 on 2022-05-05 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendedor',
            new_name='Funcionario',
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataLocacao', models.DateField()),
                ('valor', models.CharField(max_length=10)),
                ('dataDevolucao', models.DateField()),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacionamento.carro')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacionamento.cliente')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estacionamento.funcionario')),
            ],
        ),
    ]
